# Generated by Django 2.2.4 on 2021-01-27 14:21
import phonenumbers
from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            phone_number_object = phonenumbers.parse(flat.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(phone_number_object):
                flat.owner_pure_phone = phonenumbers.format_number(phone_number_object, phonenumbers.PhoneNumberFormat.E164)
                flat.save()


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20210127_1719'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers, move_backward),
    ]
