# Generated by Django 2.2.4 on 2021-01-27 15:10

from django.db import migrations


def fill_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        p = Owner.objects.get_or_create(name=flat.owner, phonenumber=flat.owners_phonenumber, pure_phone=flat.owner_pure_phone)


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner_model, move_backward),
    ]
