# Generated by Django 2.2.4 on 2021-01-27 19:03

from django.db import migrations


def fill_flat_owners_model(apps, schema_editor):
    flats = apps.get_model('property', 'Flat').objects.all()
    owners = apps.get_model('property', 'Owner').objects.all()

    for owner in owners:
        for flat in flats:
            if flat.owner == owner.name:
                flat.owners.add(owner)
                owner.flats.add(flat)


def move_backward(apps, schema_editor):
    flats = apps.get_model('property', 'Flat').objects.all()

    for flat in flats:
        flat.owners.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210127_1810'),
    ]

    operations = [
        migrations.RunPython(fill_flat_owners_model, move_backward),
    ]
