# Generated by Django 2.2.4 on 2021-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210128_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.IntegerField(blank=True, db_index=True, null=True,
                                      verbose_name='Количество жилых '
                                                   'кв.метров'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(db_index=True,
                                          verbose_name='Новостройка'),
        ),
    ]
